name: ci

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  cmake_build:
    name: cmake_build
    runs-on: ubuntu-latest

    steps:
      - name: setup
        run: |
         sudo apt-get update
         sudo apt-get install cmake g++ clang-15 libgtest-dev libgmock-dev make
      - uses: actions/checkout@v3
      - name: git submodule update
        run: |
          git submodule update --init --recursive
      - name: Generate makefile using CMake
        run: |
          mkdir cmake_build
          cd cmake_build
          cmake .. -DCMAKE_CXX_COMPILER=/usr/bin/clang++-15
      - name: Run make
        run: |
          cd cmake_build
          make -j$(nproc)
      - name: Run unittests
        run: |
          cd cmake_build
          ctest -j$(nproc)
      - name: Run driver tests
        run: |
          cd cmake_build
          ./tscpp